### ISSUE TITLE
Conversion error message

### ISSUE THREAD

**Issue by lesichkovm** [AletheiaWareLLC/conveyservergo#1]
![image](https://user-images.githubusercontent.com/7744963/127438101-5de9b720-9276-47a8-a478-8df4c42b811c.png)

**Comment by stuartmscott** [comment]
Hey @lesichkovm thanks for reporting this!

I've resolved the issue, and pushed the update to the server - let me know if you encounter any other issues.

I have credited some coins to your Convey account as a token of my gratitude :)

BTW this project has moved to https://github.com/AletheiaWareLLC/conveyearthgo.

**Comment by lesichkovm** [comment]
Thank you @stuartmscott  for fixing it this quick. Great job
